"""Add ReferenceRange model

Revision ID: bccd7f334593
Revises: 553e601f77f5
Create Date: 2025-06-30 10:26:16.251595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bccd7f334593'
down_revision = '553e601f77f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_reference_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=100), nullable=False),
    sa.Column('normal_min', sa.Float(), nullable=False),
    sa.Column('normal_max', sa.Float(), nullable=False),
    sa.Column('units', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('reference_ranges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_ranges',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('test_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('parameter', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('min_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('max_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='reference_ranges_pkey')
    )
    op.drop_table('test_reference_ranges')
    # ### end Alembic commands ###
