"""Add parameter column to lab_tests with default

Revision ID: 0c7a8d2b9c21
Revises: bccd7f334593
Create Date: 2025-06-30 14:15:24.326036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c7a8d2b9c21'
down_revision = 'bccd7f334593'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lab_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parameter', sa.String(length=100), server_default='Pending', nullable=False))
        batch_op.drop_column('test_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_tests") as batch_op:
     batch_op.alter_column('parameter', server_default=None)

    # ### end Alembic commands ###
