"""Add TestReferenceRange model

Revision ID: 553e601f77f5
Revises: e9aa3b090ca8
Create Date: 2025-06-29 23:12:25.972482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553e601f77f5'
down_revision = 'e9aa3b090ca8'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table("lab_tests") as batch_op:
        batch_op.add_column(sa.Column('parameter', sa.String(length=100), nullable=False, server_default="Pending"))

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reference_ranges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_type', sa.String(), nullable=False),
    sa.Column('parameter', sa.String(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table("lab_tests") as batch_op:
        batch_op.drop_column('parameter')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reference_ranges')
    # ### end Alembic commands ###
