"""Make test_type column nullable

Revision ID: 5808603aa33d
Revises: 24b2e228cc9a
Create Date: 2025-07-03 11:15:58.766010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5808603aa33d'
down_revision = '24b2e228cc9a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_reference_ranges', schema=None) as batch_op:
        batch_op.alter_column('test_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_reference_ranges', schema=None) as batch_op:
        batch_op.alter_column('test_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
